version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: kada-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
